version: '3.8'

services:
  restserver:
    build:
      context: ./REST
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      webserver:
        condition: service_started
      database:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      minio:
        condition: service_started
      rabbitmq:
        condition: service_started
      kibana:
        condition: service_started
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./webserver/src:/app/src
      - ./webserver/public:/app/public

  ocr-service:
    build:
      context: ./OCR
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      elasticsearch:
        condition: service_healthy
      minio:
        condition: service_started
      rabbitmq:
        condition: service_started
      kibana:
        condition: service_started
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200


  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paperless
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin-password
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-storage:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "logger.level=ERROR"
    ports:
      - "9200:9200" # Elasticsearch API
    volumes:
      - elastic-storage:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # http no s for elasticsearch
      - SERVER_SSL_ENABLED=false
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none # Disable certificate validation for development
    ports:
      - "9092:5601" # Kibana UI exposed on port 9092
    depends_on:
      - elasticsearch


volumes:
  db:
  minio-storage: {}
  elastic-storage: