version: '3.8'

services:
  restserver:
    build:
      context: ./REST
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - webserver
      - database

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./webserver/src:/app/src
      - ./webserver/public:/app/public

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paperless
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data