version: '3.8'

services:
  restserver:
    build:
      context: ./REST
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - webserver

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./webserver/src:/app/src
      - ./webserver/public:/app/public
