version: '3.8'

services:
  restserver:
    build:
      context: ./REST
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - webserver
      - database

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./webserver/src:/app/src
      - ./webserver/public:/app/public

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paperless
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin-password
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-storage:/data


volumes:
  db:
  minio-storage: {}